#!/usr/bin/env bash
# backup and compress my databases

# Dump all databases
mysqldump --all-databases -u root --password="$1" > backup.sql

# Compress the dump
file_name="$(date +%m-%d-%Y).tar.gz"
tar -czvf "$file_name" backup.sql

# Clean up
rm backup.sql
