#!/usr/bin/env bash
# This script displays Best School 10 times, but for the 9th iteration, displays Hi.

a=0
while [ "$a" -lt 10 ]; do
  if [ $a -eq 9 ]; then
    echo "Hi"
  fi
  echo "Best School $a"
  ((a++))
done
